### ISSUE TITLE
Question - MODAL_SELECTED_ITEM.SURVEY_QUESTION

### ISSUE THREAD

**Issue by valenipes** [DoFabien/OsmGo#186] opened 2024-08-16 14:21 UTC
I'm on Android, version 1.7.0. On every object I select, I find this line:

MODAL_SELECTED_ITEM.SURVEY_QUESTION

and then I can choose between yes or no. 

I've read the docs and didn't find anything. Can somebody explain what it means?

Screenshot:
![Screenshot_20240816-160522_Osm Go!](https://github.com/user-attachments/assets/5e40f7a1-8183-4168-a920-1670c1bf6a3e)

**Comment by dotcs** [comment] 2024-08-17 10:49
It seems this string is not translated in any other language than French.

https://github.com/OsmTravel/OsmGo/blob/11390e2a9322d1b91a24d717aa8462404c0c1c72/src/assets/i18n/fr.json#L181

The question asked is if this object still does exist. This should also be translated to other languages as I have the same issue in the German interface.

**Comment by dotcs** [comment] 2024-08-17 11:34
Closed as duplicate of #183. Still thanks a lot for the report!

**Closed as completed by dotcs** 2024-08-17 11:34 UTC
